version: "2"

services:
    web:
        image: nginx:alpine
        ports:
            - "127.0.0.1:5080:80"
        volumes:
            - ".docker/nginx-static.conf:/etc/nginx/conf.d/default.conf"
            - "./web:/var/www/app"
